// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90wh-Sf7nTChe01brt_glhJS2XmD_C9Y',
    appId: '1:871567379419:web:e612ccf2967d9f12dab5fe',
    messagingSenderId: '871567379419',
    projectId: 'projetlicence-18d64',
    authDomain: 'projetlicence-18d64.firebaseapp.com',
    storageBucket: 'projetlicence-18d64.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8vJIKN6iXq5OK4InjuT_uQQDjh_YeaU4',
    appId: '1:871567379419:android:39cd16c2f30fc64ddab5fe',
    messagingSenderId: '871567379419',
    projectId: 'projetlicence-18d64',
    storageBucket: 'projetlicence-18d64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhrKexXYPBtuJ9PswD-Ezi8y-MUUVkq54',
    appId: '1:871567379419:ios:e11faf35b35d1a10dab5fe',
    messagingSenderId: '871567379419',
    projectId: 'projetlicence-18d64',
    storageBucket: 'projetlicence-18d64.appspot.com',
    iosBundleId: 'com.example.projetlicence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhrKexXYPBtuJ9PswD-Ezi8y-MUUVkq54',
    appId: '1:871567379419:ios:e11faf35b35d1a10dab5fe',
    messagingSenderId: '871567379419',
    projectId: 'projetlicence-18d64',
    storageBucket: 'projetlicence-18d64.appspot.com',
    iosBundleId: 'com.example.projetlicence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD90wh-Sf7nTChe01brt_glhJS2XmD_C9Y',
    appId: '1:871567379419:web:f733c977e19084e0dab5fe',
    messagingSenderId: '871567379419',
    projectId: 'projetlicence-18d64',
    authDomain: 'projetlicence-18d64.firebaseapp.com',
    storageBucket: 'projetlicence-18d64.appspot.com',
  );
}
